version: '3.1'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "443:443"  
      - "80:80"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx1:
    image: nacamza/githubactions
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=docker1.viziongps.net
      - LETSENCRYPT_HOST=docker1.viziongps.net
      - LETSENCRYPT_EMAIL=ncano@globalis-sa.com         

  nginx2: 
    image: grafana/grafana
    expose:
      - "3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=docker2.viziongps.net
      - LETSENCRYPT_HOST=docker2.viziongps.net
      - LETSENCRYPT_EMAIL=ncano@globalis-sa.com     
volumes: 
  certs:
  html:
  vhostd:
