version: "3.3"

services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.back.address=:4000"
      - "--entrypoints.api.address=:8000"
      
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true" 
      
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=nahuelcano@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
      - "4000:4000"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  frontend:
    image: dockerfrontend
    expose: 
      - "80"    
    labels:  
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`docker1.viziongps.net`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"   

  backend:
    image: dockerbackend
    expose: 
      - "4000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`docker1.viziongps.net`)"
      - "traefik.http.routers.backend.entrypoints=back"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=4000"
      # Enable gzip compression
      - "traefik.http.middlewares.test-compress.compress=true"      
    volumes:
      - /home/yallacollect/upload_excel_files:/uploads
      - /home/yallacollect/logos:/logos      


  apiexpress:
    image: dockerapiexpress
    expose: 
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apiexpress.rule=Host(`docker1.viziongps.net`)"
      - "traefik.http.routers.apiexpress.entrypoints=api"
      - "traefik.http.routers.apiexpress.tls.certresolver=myresolver"
      - "traefik.http.services.apiexpress.loadbalancer.server.port=8000"
    volumes:
      - /home/yallacollect/upload_excel_files:/uploads
      - /home/yallacollect/logos:/logos    

