## Configuracion de seguridad (TLS1.2 minimo)
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
## Para usar certificados pagos
tls:
  certificates:
    - certFile: /cert/yallacollect.crt
      keyFile:  /cert/yallacollect.key
      stores:
        - default 
## Redirecciono fuera la red docker el Host(`server.nginx.app.test`) con el servicio "apache-service" a la url: "http://127.0.0.1" 
http:
  routers:
    apache:
      rule: "Host(`server.nginx.app.test`)"
      service: apache-service

  services:
    apache-service:   
      loadBalancer:
        servers:
          - url: "http://127.0.0.1"
