---
global:
  sendAnonymousUsage: false
  checkNewVersion: false

api:
  insecure: false
#  dashboard: true
#  debug: true

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    #watch: true
    swarmMode: false

  file:
    directory: /etc/traefik/dynamic
    #watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  back:
    address: ":4000"
  apiexpress:
    address: ":8000"

certificatesResolvers:
  myresolver:
    acme:
      email: nahuelcano@gmail.com
#      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /letsencrypt/acme.json
      keyType: EC256
      httpChallenge:
        entrypoint: web

#log:
#  filePath: "/traefik.log"        
#  level: ERROR
#  format: json 
